# Generated by Django 5.0.2 on 2024-03-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_recipe_author_recipe_created_on_recipe_update_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.CharField(default="Arthur Lluisma", max_length=100),
        ),
    ]
